CREATE TABLE TSTUDENTS (
    STUDENTID BIGINT PRIMARY KEY,
    NAME NVARCHAR(MAX),
    DATEOFBIRTH DATE,
	UNIVERSITYCOURSE NVARCHAR(MAX),
	STARTDATE DATE,
	ENDDATE DATE,
    WELSHLANGUAGEPROFICIENCY INT,
	RETIREMENTDATE datetime
);

