IF EXISTS(SELECT TOP 1 1 FROM sys.procedures WHERE name='SP_GetStudentInfo' AND type='P')
DROP PROCEDURE SP_GetStudentInfo
GO 
CREATE PROC SP_GetStudentInfo
AS BEGIN
	SELECT studentid,name,DATEOFBIRTH,UNIVERSITYCOURSE,STARTDATE,ENDDATE,WELSHLANGUAGEPROFICIENCY,RETIREMENTDATE FROM TSTUDENTS WHERE RetirementDate IS NULL
END

