IF EXISTS(SELECT TOP 1 1 FROM SYS.PROCEDURES WHERE NAME='SP_INSERTORUPDATESTUDENT' AND TYPE='P')
DROP PROCEDURE SP_INSERTORUPDATESTUDENT
GO 
CREATE PROC SP_INSERTORUPDATESTUDENT
(
	@STUDENTID BIGINT,
	@NAME NVARCHAR(MAX),
	@DATEOFBIRTH DATE,
	@UNIVERSITYCOURSE NVARCHAR(MAX),
	@STARTDATE DATE,
	@ENDDATE DATE,
    @WELSHLANGUAGEPROFICIENCY INT
)

AS  
IF @STUDENTID = 0
    BEGIN
        SELECT @STUDENTID = ISNULL(MAX(STUDENTID), 0) + 1 FROM TSTUDENTS
    END
IF NOT EXISTS (SELECT * FROM  TSTUDENTS WHERE STUDENTID = @STUDENTID)  
BEGIN  
 INSERT INTO TSTUDENTS(STUDENTID,NAME,DATEOFBIRTH,UNIVERSITYCOURSE,STARTDATE,ENDDATE,WELSHLANGUAGEPROFICIENCY)  
 VALUES(@STUDENTID,@NAME,@DATEOFBIRTH,@UNIVERSITYCOURSE,@STARTDATE,@ENDDATE,@WELSHLANGUAGEPROFICIENCY)  
END  
ELSE  
BEGIN  
 UPDATE TSTUDENTS SET NAME=@NAME,WELSHLANGUAGEPROFICIENCY=@WELSHLANGUAGEPROFICIENCY WHERE STUDENTID = @STUDENTID  
END  